# Generated by Django 6.0.4 on 2026-04-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(max_length=50, unique=True)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('transmission', models.CharField(choices=[('Auto', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT')], max_length=10)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('write_off_status', models.CharField(choices=[('Repairable', 'Repairable'), ('Statutory', 'Statutory')], max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
