# Generated by Django 6.0.4 on 2026-04-11 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('Used', 'Used'), ('New', 'Aftermarket New'), ('Damaged', 'Damaged')], default='Used', max_length=20)),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('Internal', 'Internal Use Only'), ('Sold', 'Sold')], default='For Sale', max_length=20)),
                ('donor_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.donorcar')),
            ],
        ),
    ]
