# Generated by Django 5.0.4 on 2026-04-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_aftermarketpart_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('items', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aftermarketpart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aftermarketpart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aftermarketpart',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='aftermarketpart',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='donorcar',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorcar',
            name='rego',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donorcar',
            name='salvage_checklist',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='condition_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='grading',
            field=models.CharField(default='Grade A', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='label_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='usage_type',
            field=models.CharField(default='Sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorcar',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donorcar',
            name='make',
            field=models.CharField(default='Toyota', max_length=50),
        ),
        migrations.AlterField(
            model_name='donorcar',
            name='stock_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='donorcar',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donorcar',
            name='write_off_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
