# Generated by Django 5.0.4 on 2026-04-17 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_invoice_remove_aftermarketpart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftermarketpart',
            name='category',
            field=models.CharField(choices=[('Oil Filters', 'Oil Filters'), ('Air Filters', 'Air Filters'), ('Cabin Filters', 'Cabin Filters'), ('Fuel Filters', 'Fuel Filters'), ('Brake Pads', 'Brake Pads'), ('Brake Rotors', 'Brake Rotors'), ('Spark Plugs', 'Spark Plugs'), ('Ignition Coils', 'Ignition Coils'), ('Wiper Blades', 'Wiper Blades'), ('Bulbs', 'Bulbs'), ('Sensors', 'Sensors'), ('Suspension', 'Suspension'), ('Cooling', 'Cooling'), ('Belts', 'Belts'), ('Batteries', 'Batteries'), ('Fluids', 'Fluids'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='aftermarketpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aftermarketpart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aftermarketpart',
            name='label_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='aftermarketpart',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aftermarketpart',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aftermarketpart',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aftermarketpart',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aftermarketpart',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
