# Generated by Django 5.0.4 on 2026-04-17 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_aftermarketpart_category_aftermarketpart_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Engine', 'Engine'), ('Transmission', 'Transmission'), ('Suspension', 'Suspension'), ('Steering', 'Steering'), ('Brakes', 'Brakes'), ('Electrical', 'Electrical'), ('Lighting', 'Lighting'), ('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Body Panels', 'Body Panels'), ('Cooling', 'Cooling'), ('Fuel System', 'Fuel System'), ('Exhaust', 'Exhaust'), ('Wheels & Tyres', 'Wheels & Tyres'), ('Doors & Windows', 'Doors & Windows'), ('Mirrors', 'Mirrors'), ('AC & Heating', 'AC & Heating'), ('Sensors', 'Sensors'), ('ECU / Modules', 'ECU / Modules'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D')], default='B', max_length=10)),
                ('rating', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('condition', models.CharField(choices=[('New Old Stock', 'New Old Stock'), ('Used Excellent', 'Used Excellent'), ('Used Good', 'Used Good'), ('Used Fair', 'Used Fair'), ('Reconditioned', 'Reconditioned'), ('Damaged', 'Damaged')], default='Used Good', max_length=50)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('usage_type', models.CharField(choices=[('FOR_SALE', 'For Sale'), ('INTERNAL_USE', 'Internal Use')], default='FOR_SALE', max_length=20)),
                ('sale_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('REMOVED', 'Removed'), ('DAMAGED', 'Damaged'), ('HOLD', 'Hold')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('shelf_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('label_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_code_value', models.CharField(blank=True, max_length=255, unique=True)),
                ('public_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='used_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.usedpart'),
        ),
    ]
